Repository SoPra18-07/Singularity, pull requests merged in 2018-06, with the labels that each got.

#100 #14 master pull to create start menu
  Singularity/Singularity/Content/Content.mgcb
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Input/IKeyListener.cs
  Singularity/Singularity/Input/IMouseListener.cs
  Singularity/Singularity/Input/InputManager.cs
  Singularity/Singularity/Input/KeyEvent.cs
  Singularity/Singularity/Input/MouseAction.cs
  Singularity/Singularity/Input/MouseEvent.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/GeneralUnit.cs
  Singularity/Singularity/Units/MilitaryUnit.cs
  Singularity/Singularity/platform/Road.cs
  Singularity/Singularity/screen/GameScreen.cs
Labels: review

#93 Added LayerConstants, closes #91
  Singularity/Singularity/Libraries/Primitives2D.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/MilitaryUnit.cs
  Singularity/Singularity/platform/PlatformBlank.cs
  Singularity/Singularity/platform/Road.cs
  Singularity/Singularity/property/LayerConstants.cs
  Singularity/Singularity/screen/GameScreen.cs
Labels: review

#57 Added resource components. closes #47
  Singularity/Singularity/Resources/EResourceType.cs
  Singularity/Singularity/Resources/IResource.cs
  Singularity/Singularity/Resources/IResources.cs
  Singularity/Singularity/Resources/Resource.cs
  Singularity/Singularity/Resources/ResourceHelper.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Utils/Geometry.cs
  Singularity/Singularity/platform/PlatformBlank.cs
Labels: review

#103 Fixed GeneralUnit compiling error
  Singularity/Singularity/Units/GeneralUnit.cs
Labels: review

#92 Added ISpatial interface, closes #70
  Singularity/Singularity/Map/Camera.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/GeneralUnit.cs
  Singularity/Singularity/Units/IUnit.cs
  Singularity/Singularity/Units/MilitaryUnit.cs
  Singularity/Singularity/platform/PlatformBlank.cs
  Singularity/Singularity/platform/Road.cs
  Singularity/Singularity/property/ISpatial.cs
  Singularity/Singularity/screen/GameScreen.cs
Labels: review

#106 Fixed member variable inconsistency
  Singularity/Singularity/Units/MilitaryUnit.cs
Labels: review

#102 #101 Updated InputManager
  Singularity/Singularity/Input/IMouseListener.cs
  Singularity/Singularity/Input/IMouseWheelListener.cs
  Singularity/Singularity/Input/InputManager.cs
  Singularity/Singularity/Input/MouseAction.cs
  Singularity/Singularity/Input/MouseEvent.cs
  Singularity/Singularity/Singularity.csproj
Labels: review

#116 fixed the InputManager. closes #115
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Input/IKeyListener.cs
  Singularity/Singularity/Input/IMouseListener.cs
  Singularity/Singularity/Input/IMouseWheelListener.cs
  Singularity/Singularity/Input/InputManager.cs
  Singularity/Singularity/Input/KeyEvent.cs
  Singularity/Singularity/Input/MouseAction.cs
  Singularity/Singularity/Input/MouseEvent.cs
Labels: review

#117 Updated platform spritesheets
  Singularity/Singularity/Content/Cones.png
  Singularity/Singularity/Content/Cylinders.png
  Singularity/Singularity/Content/Dome.png
  Singularity/Singularity/Content/PlatformBasic.png
Labels: review

#121 Removed using directive, that was causing an error in svn, and also o…
  Singularity/Singularity/serialization/XSerializer.cs
Labels: review

#120 Implementation of PlatformActions - closes #71
  .travis.yml
  Singularity/Singularity.sln
  Singularity/Singularity/Exceptions/NoSuchElementException.cs
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Input/MouseAction.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Map/ResourceMap.cs
  Singularity/Singularity/Map/StructureMap.cs
  Singularity/Singularity/Platform/Action.cs
  Singularity/Singularity/Platform/IPlatformAction.cs
  Singularity/Singularity/Platform/Job.cs
  Singularity/Singularity/Platform/JobType.cs
  Singularity/Singularity/Platform/PlatformActionState.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/ProduceResource.cs
  Singularity/Singularity/Platform/Road.cs
  Singularity/Singularity/Properties/AssemblyInfo.cs
  Singularity/Singularity/Property/IDraw.cs
  Singularity/Singularity/Property/ISpatial.cs
  Singularity/Singularity/Property/IUpdate.cs
  Singularity/Singularity/Property/LayerConstants.cs
  Singularity/Singularity/Resources/EResourceType.cs
  Singularity/Singularity/Resources/IResource.cs
  Singularity/Singularity/Resources/Resource.cs
  Singularity/Singularity/Screen/GameScreen.cs
  Singularity/Singularity/Screen/IScreen.cs
  Singularity/Singularity/Screen/IScreenManager.cs
  Singularity/Singularity/Screen/RenderLowerScreen.cs
  Singularity/Singularity/Screen/StackScreenManager.cs
  Singularity/Singularity/Screen/UpdateLowerScreen.cs
  Singularity/Singularity/Serialization/CyclicDummy.cs
  Singularity/Singularity/Serialization/SerializationDummy.cs
  Singularity/Singularity/Serialization/XSerializer.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/GeneralUnit.cs
  Singularity/Singularity/Units/IUnit.cs
  Singularity/Singularity/Units/JobType.cs
  Singularity/Singularity/Units/MilitaryUnit.cs
  Singularity/Singularity/Units/Pathfinding.cs
  Singularity/Singularity/Units/Task.cs
  Singularity/Singularity/Utils/Optional.cs
  Singularity/Singularity/Utils/Pair.cs
  Singularity/Singularity/Utils/Triple.cs
  Singularity/Singularity/packages.config
  documents/Architecture/Singularity.ncp
Labels: Blueprinting, Platforms, review

#97 Update .travis.yml
  .travis.yml
Labels: review

#123 Delete Job.cs
  Singularity/Singularity/Platform/Job.cs
  Singularity/Singularity/Singularity.csproj
Labels: review

#125 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: review

#122 Delete packages.config
  Singularity/Singularity/packages.config
Labels: review

#107 Added the specified requirements. closes #80
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Libraries/Primitives2D.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Map/Properties/MapConstants.cs
  Singularity/Singularity/Platform/ProduceResource.cs
  Singularity/Singularity/Resources/IResource.cs
  Singularity/Singularity/Resources/Resource.cs
  Singularity/Singularity/Resources/ResourceHelper.cs
  Singularity/Singularity/Screen/GameScreen.cs
Labels: Resource, review

#127 #76 implement the energy facility
  Singularity/Singularity/Content/Content.mgcb
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Platform/EPlatformType.cs
  Singularity/Singularity/Platform/EnergyFacility.cs
  Singularity/Singularity/Platform/Junkyard.cs
  Singularity/Singularity/Platform/Mine.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/ProduceResource.cs
  Singularity/Singularity/Platform/Quarry.cs
  Singularity/Singularity/Platform/Well.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/StoryManager/StoryManager.cs
Labels: review

#124 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: review

#129 Incorporated ISpatial into MilitaryUnits and Roads, closes #111
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Platform/Road.cs
  Singularity/Singularity/Units/MilitaryUnit.cs
  Singularity/Singularity/Utils/Geometry.cs
Labels: review

#132 finished slider class
  Singularity/Singularity/Screen/Slider.cs
  Singularity/Singularity/Screen/WindowItem.cs
  Singularity/Singularity/Singularity.csproj
Labels: review

#135 Added the FogOfWar to the game, closes #79
  Singularity/Singularity/Content/Content.mgcb
  Singularity/Singularity/Content/MockUpBackground.png
  Singularity/Singularity/Exceptions/UnsupportedTextureSizeException.cs
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Libraries/Primitives2D.cs
  Singularity/Singularity/Map/FogOfWar.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Map/Properties/MapConstants.cs
  Singularity/Singularity/Map/StructureMap.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Property/IRevealing.cs
  Singularity/Singularity/Property/LayerConstants.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/MilitaryUnit.cs
  Singularity/Singularity/Utils/Geometry.cs
Labels: review

#137 Improved the InputManager, closes #136
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Input/EClickType.cs
  Singularity/Singularity/Input/IMouseClickListener.cs
  Singularity/Singularity/Input/IMouseListener.cs
  Singularity/Singularity/Input/IMousePositionListener.cs
  Singularity/Singularity/Input/IMouseWheelListener.cs
  Singularity/Singularity/Input/InputManager.cs
  Singularity/Singularity/Input/MouseEvent.cs
  Singularity/Singularity/Map/Camera.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/MilitaryUnit.cs
Labels: review

#138 changed WindowItem name to IWindowItem
  Singularity/Singularity/Screen/IWindowItem.cs
  Singularity/Singularity/Singularity.csproj
Labels: review

#126 button class finished without the use of an input manager
  Singularity/Singularity/Screen/Button.cs
  Singularity/Singularity/Screen/IWindowItem.cs
  Singularity/Singularity/Singularity.csproj
Labels: Input, UI, review

#140 Fixed issue with hovering == released
  Singularity/Singularity/Screen/Button.cs
Labels: review

#139 Add direct link to branch-network
  README.md
Labels: review

#142 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: review

#155 #149 background grid texture
  Singularity/Singularity/Content/MockUpBackground.png
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
Labels: review

#141 Code for SoundManager added
  Singularity/Singularity/Content/Content.mgcb
  Singularity/Singularity/Content/Sound/SFX/ButtonPress.wav
  Singularity/Singularity/Content/Sound/Tutorial_Build.mp3
  Singularity/Singularity/Content/Sound/UI/ButtonPress.wav
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Sound/SoundClass.cs
  Singularity/Singularity/Sound/SoundManager.cs
  Singularity/Singularity/Sound/SoundPhase.cs
Labels: review

#159 Fixed various bugs
  Singularity/Singularity/Map/CollisionMap.cs
  Singularity/Singularity/Map/FogOfWar.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Map/Properties/MapConstants.cs
  Singularity/Singularity/Map/ResourceMap.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/ProduceResource.cs
  Singularity/Singularity/Property/ICollider.cs
  Singularity/Singularity/Property/LayerConstants.cs
  Singularity/Singularity/Resources/IResource.cs
  Singularity/Singularity/Resources/Resource.cs
  Singularity/Singularity/Resources/ResourceHelper.cs
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/GeneralUnit.cs
  Singularity/Singularity/Units/IUnit.cs
  Singularity/Singularity/Units/MilitaryUnit.cs
  Singularity/Singularity/Utils/IdGenerator.cs
Labels: review

#157 Modified Center property to properly point to the center of the base …
  Singularity/Singularity/Platform/EnergyFacility.cs
  Singularity/Singularity/Platform/Junkyard.cs
  Singularity/Singularity/Platform/Mine.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/Quarry.cs
  Singularity/Singularity/Platform/Road.cs
  Singularity/Singularity/Platform/Well.cs
Labels: review

#160 #118 animate main menu
  Singularity/Singularity/Content/MockUpBackground.png
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Libraries/Animations.cs
  Singularity/Singularity/Platform/Road.cs
  Singularity/Singularity/Screen/Button.cs
  Singularity/Singularity/Screen/ITransitionableMenu.cs
  Singularity/Singularity/Screen/ScreenClasses/AchievementsScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/GameModeSelectScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/LoadSelectScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/LoadingScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MainMenuManagerScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MainMenuScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MenuBackgroundScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/OptionsScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/SplashScreen.cs
  Singularity/Singularity/Singularity.csproj
Labels: review

#166 Improved the fog of war
  Singularity/Singularity/Content/Content.mgcb
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Map/Camera.cs
  Singularity/Singularity/Map/FogOfWar.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Map/StructureMap.cs
  Singularity/Singularity/Platform/Road.cs
  Singularity/Singularity/Property/ISpatial.cs
  Singularity/Singularity/Resources/Resource.cs
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
  Singularity/Singularity/Units/MilitaryUnit.cs
Labels: review

#158 added a FillCircle and StrokedCircle to primitives Library
  Singularity/Singularity/Libraries/Primitives2D.cs
Labels: review

#170 Various bug fixes
  Singularity/Singularity/Map/CollisionMap.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Map/Properties/MapConstants.cs
  Singularity/Singularity/Map/ResourceMap.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/ProduceResource.cs
  Singularity/Singularity/Property/ICollider.cs
  Singularity/Singularity/Property/LayerConstants.cs
  Singularity/Singularity/Resources/IResource.cs
  Singularity/Singularity/Resources/Resource.cs
  Singularity/Singularity/Resources/ResourceHelper.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/GeneralUnit.cs
  Singularity/Singularity/Units/IUnit.cs
  Singularity/Singularity/Units/MilitaryUnit.cs
  Singularity/Singularity/Utils/IdGenerator.cs
Labels: review

#172 Fixed IRevealing Center property
  Singularity/Singularity/Platform/Junkyard.cs
  Singularity/Singularity/Platform/Mine.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/Quarry.cs
  Singularity/Singularity/Platform/Well.cs
Labels: review

#173 Grid added to both content folder and Content.mgcb
  Singularity/Singularity/Content/Content.mgcb
  Singularity/Singularity/Content/backgroundGrid.png
Labels: review

#177 #118 create menu second attempt
  Singularity/Singularity/Libraries/Animations.cs
  Singularity/Singularity/Screen/Button.cs
  Singularity/Singularity/Screen/ITransitionableMenu.cs
  Singularity/Singularity/Screen/ScreenClasses/AchievementsScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/GameModeSelectScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/LoadSelectScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/LoadingScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MainMenuManagerScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MainMenuScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MenuBackgroundScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/OptionsScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/SplashScreen.cs
  Singularity/Singularity/Screen/StackScreenManager.cs
  Singularity/Singularity/Singularity.csproj
Labels: review

#168 Changed icon
  Singularity/Singularity/Icon.ico
Labels: review

#178 Fixed typo in "Achievements"
  Singularity/Singularity/Screen/ScreenClasses/MainMenuScreen.cs
Labels: review

#179 small fixes to the button scaling function
  Singularity/Singularity/Screen/Button.cs
Labels: review

#180 Slider overloads (value display)
  Singularity/Singularity/Screen/Slider.cs
Labels: review

#190 Delete JobType.cs
  Singularity/Singularity/Platform/JobType.cs
Labels: review

#196 Mostly changes to the ScreenManager
  Singularity/Singularity/Content/Content.mgcb
  Singularity/Singularity/Content/Sound/Singularity_Menu.mp3
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Screen/IScreen.cs
  Singularity/Singularity/Screen/RenderLowerScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/AchievementsScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/GameModeSelectScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/GamePauseScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/LoadSelectScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/LoadingScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MainMenuManagerScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MainMenuScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MenuBackgroundScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/OptionsScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/SaveGameScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/SplashScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/StatisticsScreen.cs
  Singularity/Singularity/Screen/StackScreenManager.cs
  Singularity/Singularity/Screen/UpdateLowerScreen.cs
  Singularity/Singularity/Singularity.csproj
Labels: review

#192 Update README.md
  README.md
Labels: review

#198 removed unneeded second input manager
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Input/InputManager2.cs
  Singularity/Singularity/Singularity.csproj
Labels: review

#204 Split sprites for platforms into two
  Singularity/Singularity/Content/PlatformBasic.png
  Singularity/Singularity/Platform/EnergyFacility.cs
  Singularity/Singularity/Platform/Junkyard.cs
  Singularity/Singularity/Platform/Mine.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/Quarry.cs
  Singularity/Singularity/Platform/Well.cs
  Singularity/Singularity/Property/LayerConstants.cs
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
Labels: review

#207 #181 useful structure and fow, closes #181 and closes #183
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Graph/Paths/DefaultPathfinding.cs
  Singularity/Singularity/Input/IMouseClickListener.cs
  Singularity/Singularity/Input/IMouseWheelListener.cs
  Singularity/Singularity/Input/InputManager.cs
  Singularity/Singularity/Map/Camera.cs
  Singularity/Singularity/Screen/EScreen.cs
  Singularity/Singularity/Screen/IScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/AchievementsScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/GameModeSelectScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/GamePauseScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/LoadSelectScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/LoadingScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MainMenuManagerScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MainMenuScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MenuBackgroundScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/OptionsScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/SaveGameScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/SplashScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/StatisticsScreen.cs
  Singularity/Singularity/Screen/StackScreenManager.cs
  Singularity/Singularity/Units/MilitaryUnit.cs
Labels: review

#209 #113 create a modular windows object
  Singularity/Singularity/Content/Content.mgcb
  Singularity/Singularity/Content/LibSans14.spritefont
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Libraries/Primitives2D.cs
  Singularity/Singularity/Platform/EnergyFacility.cs
  Singularity/Singularity/Screen/Button.cs
  Singularity/Singularity/Screen/EScreen.cs
  Singularity/Singularity/Screen/IWindowItem.cs
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/PopupWindow.cs
  Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
  Singularity/Singularity/Screen/Slider.cs
  Singularity/Singularity/Screen/TextField.cs
  Singularity/Singularity/Screen/WindowObject.cs
  Singularity/Singularity/Singularity.csproj
Labels: review

#208 #31 enemy units
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/EnemyUnit.cs
Labels: review

#213 close #211 close #210
  Singularity/Singularity/Screen/WindowObject.cs
  Singularity/Singularity/Singularity.csproj
Labels: review

#219 Changed colors of military unit select/deselect
  Singularity/Singularity/Units/MilitaryUnit.cs
Labels: review

#220 #90 implement the distribution manager
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Levels/Skirmish.cs
  Singularity/Singularity/Manager/DistributionManager.cs
  Singularity/Singularity/Platform/Mine.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/Quarry.cs
  Singularity/Singularity/Platform/Storage.cs
  Singularity/Singularity/Platform/Well.cs
  Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
  Singularity/Singularity/Screen/Slider.cs
  Singularity/Singularity/Units/GeneralUnit.cs
Labels: review

#221 added selection box and military shooting
  Singularity/Singularity/Content/Content.mgcb
  Singularity/Singularity/Content/Sound/SFX/LaserSound.wav
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/MilitaryUnit.cs
  Singularity/Singularity/Units/SelectionBox.cs
Labels: review

#224 #163 finish military units
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Levels/Skirmish.cs
  Singularity/Singularity/Levels/Tutorial.cs
  Singularity/Singularity/Map/Camera.cs
  Singularity/Singularity/Map/CollisionMap.cs
  Singularity/Singularity/Map/CollisionNode.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Map/Properties/MapConstants.cs
  Singularity/Singularity/Platform/CommandCenter.cs
  Singularity/Singularity/Platform/Factory.cs
  Singularity/Singularity/Platform/Mine.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/Road.cs
  Singularity/Singularity/Platform/Storage.cs
  Singularity/Singularity/Screen/ScreenClasses/GameModeSelectScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/LoadingScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MainMenuManagerScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MainMenuScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/OptionsScreen.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/MilitaryPathfinder.cs
  Singularity/Singularity/Units/MilitaryUnit.cs
  Singularity/Singularity/app.config
  Singularity/Singularity/packages.config
  Singularity/packages/C5.2.5.3/C5.2.5.3.nupkg
  Singularity/packages/C5.2.5.3/lib/net35/C5.dll
  Singularity/packages/C5.2.5.3/lib/net35/C5.xml
  Singularity/packages/C5.2.5.3/lib/net40/C5.dll
  Singularity/packages/C5.2.5.3/lib/net40/C5.xml
  Singularity/packages/C5.2.5.3/lib/net45/C5.dll
  Singularity/packages/C5.2.5.3/lib/net45/C5.xml
  Singularity/packages/C5.2.5.3/lib/netstandard1.0/C5.dll
  Singularity/packages/C5.2.5.3/lib/netstandard1.0/C5.xml
  Singularity/packages/C5.2.5.3/lib/portable-net40+sl5+win8+wp8+wpa81/C5.dll
  Singularity/packages/C5.2.5.3/lib/portable-net40+sl5+win8+wp8+wpa81/C5.xml
  Singularity/packages/C5.2.5.3/lib/portable-net45+win8+wp8+wpa81/C5.dll
  Singularity/packages/C5.2.5.3/lib/portable-net45+win8+wp8+wpa81/C5.xml
  Singularity/packages/EpPathFinding.cs.1.4.2/EpPathFinding.cs.1.4.2.nupkg
  Singularity/packages/EpPathFinding.cs.1.4.2/lib/EpPathFinding.cs.dll
Labels: review

#223 closes #185 Resources
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Graph/Paths/PathManager.cs
  Singularity/Singularity/Input/IMouseClickListener.cs
  Singularity/Singularity/Input/InputManager.cs
  Singularity/Singularity/Libraries/Bloom Filter.cs
  Singularity/Singularity/Libraries/Primitives2D.cs
  Singularity/Singularity/Manager/Director.cs
  Singularity/Singularity/Manager/DistributionManager.cs
  Singularity/Singularity/Manager/MilitaryManager.cs
  Singularity/Singularity/Map/Camera.cs
  Singularity/Singularity/Map/FogOfWar.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Map/ResourceMap.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/ProduceResource.cs
  Singularity/Singularity/Property/LayerConstants.cs
  Singularity/Singularity/Resources/MapResource.cs
  Singularity/Singularity/Resources/Resource.cs
  Singularity/Singularity/Resources/ResourceHelper.cs
  Singularity/Singularity/Screen/ScreenClasses/GameModeSelectScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/OptionsScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/PopupWindow.cs
  Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
  Singularity/Singularity/Screen/Slider.cs
  Singularity/Singularity/Screen/TextField.cs
  Singularity/Singularity/Screen/WindowObject.cs
  Singularity/Singularity/Sound/SoundManager.cs
  Singularity/Singularity/Units/EnemyUnit.cs
  Singularity/Singularity/Units/GeneralUnit.cs
  Singularity/Singularity/Units/Task.cs
  Singularity/Singularity/Utils/Geometry.cs
  Singularity/Singularity/Utils/IdGenerator.cs
  Singularity/Singularity/Utils/Optional.cs
  Singularity/packages/C5.2.5.3/lib/net35/C5.xml
  Singularity/packages/C5.2.5.3/lib/net40/C5.xml
  Singularity/packages/C5.2.5.3/lib/net45/C5.xml
  Singularity/packages/C5.2.5.3/lib/netstandard1.0/C5.xml
  Singularity/packages/C5.2.5.3/lib/portable-net40+sl5+win8+wp8+wpa81/C5.xml
  Singularity/packages/C5.2.5.3/lib/portable-net45+win8+wp8+wpa81/C5.xml
Labels: review

#226 Buildings are now transparent while they are blueprints
  Singularity/Singularity/Platform/PlatformBlank.cs
Labels: review

#235 closes #60 Resource Colors
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Graph/Paths/DefaultPathfinding.cs
  Singularity/Singularity/Input/IMouseClickListener.cs
  Singularity/Singularity/Input/InputManager.cs
  Singularity/Singularity/Levels/Achievements.cs
  Singularity/Singularity/Levels/LevelType.cs
  Singularity/Singularity/Levels/Skirmish.cs
  Singularity/Singularity/Levels/Tutorial.cs
  Singularity/Singularity/Libraries/Primitives2D.cs
  Singularity/Singularity/Manager/Director.cs
  Singularity/Singularity/Manager/StoryManager.cs
  Singularity/Singularity/Map/Camera.cs
  Singularity/Singularity/Map/CollisionMap.cs
  Singularity/Singularity/Map/CollisionNode.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Platform/EnergyFacility.cs
  Singularity/Singularity/Platform/Factory.cs
  Singularity/Singularity/Platform/Mine.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/Quarry.cs
  Singularity/Singularity/Platform/Storage.cs
  Singularity/Singularity/Platform/Well.cs
  Singularity/Singularity/Resources/Resource.cs
  Singularity/Singularity/Resources/ResourceHelper.cs
  Singularity/Singularity/Screen/IWindowItem.cs
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MainMenuManagerScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/MainMenuScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/OptionsScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/PopupWindow.cs
  Singularity/Singularity/Screen/ScreenClasses/SplashScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
  Singularity/Singularity/Screen/Slider.cs
  Singularity/Singularity/Screen/WindowObject.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/EnemyUnit.cs
  Singularity/Singularity/Units/GeneralUnit.cs
  Singularity/Singularity/Units/MilitaryPathfinder.cs
  Singularity/Singularity/Units/MilitaryUnit.cs
  Singularity/Singularity/Units/SelectionBox.cs
  Singularity/Singularity/Utils/Geometry.cs
  Singularity/Singularity/Utils/Pair.cs
  Singularity/Singularity/Utils/Triple.cs
Labels: review

#234 close #229 window minimized input fix
  Singularity/Singularity/Screen/WindowObject.cs
Labels: review

#246 slider modification
  Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
  Singularity/Singularity/Screen/Slider.cs
Labels: review

#245 #225 finish the distribution manager
  Singularity/Singularity/Levels/Skirmish.cs
  Singularity/Singularity/Manager/DistributionManager.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Units/GeneralUnit.cs
  Singularity/Singularity/Units/Task.cs
Labels: review

#248 #228 improved bounding boxes for platforms
  Singularity/Singularity/Levels/Tutorial.cs
  Singularity/Singularity/Map/Camera.cs
  Singularity/Singularity/Map/CollisionMap.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Platform/CommandCenter.cs
  Singularity/Singularity/Platform/EnergyFacility.cs
  Singularity/Singularity/Platform/Factory.cs
  Singularity/Singularity/Platform/Junkyard.cs
  Singularity/Singularity/Platform/Mine.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/Quarry.cs
  Singularity/Singularity/Platform/Storage.cs
  Singularity/Singularity/Platform/Well.cs
  Singularity/Singularity/Property/GlobalVariables.cs
  Singularity/Singularity/Property/ICollider.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/EnemyUnit.cs
  Singularity/Singularity/Units/MilitaryPathfinder.cs
  Singularity/Singularity/Units/MilitaryUnit.cs
Labels: review

#252 Fixed platform center and placement issues
  Singularity/Singularity/Platform/CommandCenter.cs
  Singularity/Singularity/Platform/EnergyFacility.cs
  Singularity/Singularity/Platform/Factory.cs
  Singularity/Singularity/Platform/Junkyard.cs
  Singularity/Singularity/Platform/Mine.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/Quarry.cs
  Singularity/Singularity/Platform/Storage.cs
  Singularity/Singularity/Platform/Well.cs
  Singularity/Singularity/Property/GlobalVariables.cs
Labels: review

#250 Implemented ability to find direct path in cases where there is no obstacle
  Singularity/Singularity/Units/MilitaryPathfinder.cs
Labels: review

#251 #201 building menu
  Singularity/Singularity/Screen/Button.cs
  Singularity/Singularity/Screen/HorizontalCollection.cs
  Singularity/Singularity/Screen/IWindowItem.cs
  Singularity/Singularity/Screen/ScreenClasses/InfoBoxWindow.cs
  Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
  Singularity/Singularity/Screen/Slider.cs
  Singularity/Singularity/Screen/TextField.cs
  Singularity/Singularity/Screen/WindowObject.cs
  Singularity/Singularity/Singularity.csproj
Labels: review

#254 See Description. closes #202 and closes #151 and closes #150
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Input/IMousePositionListener.cs
  Singularity/Singularity/Input/InputManager.cs
  Singularity/Singularity/Levels/Skirmish.cs
  Singularity/Singularity/Levels/Tutorial.cs
  Singularity/Singularity/Manager/DistributionManager.cs
  Singularity/Singularity/Map/Camera.cs
  Singularity/Singularity/Map/FogOfWar.cs
  Singularity/Singularity/Map/Map.cs
  Singularity/Singularity/Map/StructureMap.cs
  Singularity/Singularity/Platform/CommandCenter.cs
  Singularity/Singularity/Platform/EPlacementType.cs
  Singularity/Singularity/Platform/EnergyFacility.cs
  Singularity/Singularity/Platform/Factory.cs
  Singularity/Singularity/Platform/Junkyard.cs
  Singularity/Singularity/Platform/Mine.cs
  Singularity/Singularity/Platform/PlatformBlank.cs
  Singularity/Singularity/Platform/PlatformFactory.cs
  Singularity/Singularity/Platform/PlatformPlacement.cs
  Singularity/Singularity/Platform/Quarry.cs
  Singularity/Singularity/Platform/Road.cs
  Singularity/Singularity/Platform/Storage.cs
  Singularity/Singularity/Platform/Well.cs
  Singularity/Singularity/Property/IRevealing.cs
  Singularity/Singularity/Property/LayerConstants.cs
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/InfoBoxWindow.cs
  Singularity/Singularity/Screen/ScreenClasses/PopupWindow.cs
  Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
  Singularity/Singularity/Screen/Slider.cs
  Singularity/Singularity/Screen/WindowObject.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/GeneralUnit.cs
  Singularity/Singularity/Units/MilitaryUnit.cs
  Singularity/Singularity/Units/SelectionBox.cs
  Singularity/Singularity/Utils/Pair.cs
  Singularity/Singularity/Utils/State3.cs
Labels: review

#256 Fixed the Viewport object to be out of date in the camera. This only …
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Levels/Skirmish.cs
  Singularity/Singularity/Levels/Tutorial.cs
  Singularity/Singularity/Map/Camera.cs
Labels: review

#260 #232 implement settler
  Singularity/Singularity/Levels/Skirmish.cs
  Singularity/Singularity/Libraries/Primitives2D.cs
  Singularity/Singularity/Manager/MilitaryManager.cs
  Singularity/Singularity/Platform/PlatformPlacement.cs
  Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
  Singularity/Singularity/Screen/Slider.cs
  Singularity/Singularity/Singularity.csproj
  Singularity/Singularity/Units/MilitaryUnit.cs
  Singularity/Singularity/Units/SelectionBox.cs
  Singularity/Singularity/Units/Settler.cs
Labels: review

#261 Fixed wrong platform showing for barracks and command center
  Singularity/Singularity/Platform/PlatformBlank.cs
Labels: review

#257 Disable ui changes due to resolution changes
  Singularity/Singularity/Screen/HorizontalCollection.cs
  Singularity/Singularity/Screen/PopupWindow.cs
  Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
  Singularity/Singularity/Screen/WindowObject.cs
  Singularity/Singularity/Singularity.csproj
Labels: review

#270 closes #240 implement the info bar
  Singularity/Singularity/Game1.cs
  Singularity/Singularity/Screen/InfoBarWindowObject.cs
  Singularity/Singularity/Screen/InfoBoxWindow.cs
  Singularity/Singularity/Screen/ScreenClasses/GamePauseScreen.cs
  Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
  Singularity/Singularity/Singularity.csproj
Labels: review
